[project]
name = 'stacks-defi-yield-optimizer'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.portfolio-vault-system]
path = 'contracts/portfolio-vault-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.yield-strategy-manager]
path = 'contracts/yield-strategy-manager.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
